name: CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t Dockerfile .

      - name: Run Docker container and generate static files
        run: |
          docker run --name my-nocodb-container my-nocodb-image
          docker cp my-nocodb-container:/usr/src/app/build ./build
          docker stop my-nocodb-container
          docker rm my-nocodb-container

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
